apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-news-clipper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-news-clipper
  template:
    metadata:
      labels:
        app: python-news-clipper
    spec:
      containers:
      - name: python-news-clipper
        image: 127.0.0.1:30500/python_news_clipper:1
        env:
        - name: MAIL_INTERVAL_MIN
          valueFrom:
            configMapKeyRef:
              name: python-news-clipper
              key: mailIntervalMin
        - name: MAIL_RECEIVER_EMAILS
          valueFrom:
            configMapKeyRef:
              name: python-news-clipper
              key: mailReceiverEmails
        - name: MAIL_SENDER_EMAIL
          valueFrom:
            secretKeyRef:
              name: python-news-clipper
              key: mailSenderEmail
        - name: MAIL_SENDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: python-news-clipper
              key: mailSenderPassword